In [89]:
import matplotlib.pyplot as plt
import pandas as pd
from classify.common import random_color_str
import seaborn as sns
import plotly.express as px

In [90]:
sns.set_style('whitegrid')

In [91]:
# Nạp dữ liệu CSV
df = pd.read_csv('datasets/global_salary/salary_data.csv', delimiter=',')
df.sample(50)

,country_name,continent_name,wage_span,median_salary,average_salary,lowest_salary,highest_salary
46,Cook Islands,Oceania,Monthly,2538.920000,2832.340000,712.570000,12574.850000
95,Iraq,Asia,Monthly,1382.380000,1573.310000,395.620000,6988.250000
25,Bosnia and Herzegovina,Europe,Monthly,1151.350000,1248.650000,313.510000,5567.570000
81,Guam,Oceania,Monthly,1270.000000,1400.000000,350.000000,6230.000000
168,Saint Kitts and Nevis,Caribbean,Monthly,1092.590000,1259.260000,318.520000,5592.590000
100,Jersey,Europe,Monthly,5817.070000,6304.880000,1585.370000,28048.780000
69,French Guiana,South America,Monthly,2896.410000,3319.240000,835.100000,14799.150000
35,Canada,Northern America,Monthly,6311.030000,7352.940000,1850.000000,32720.590000
82,Guatemala,Central America,Monthly,1222.650000,1335.880000,337.150000,5954.200000
4,American Samoa,Oceania,Monthly,1390.000000,1570.000000,400.000000,6980.000000
50,Cuba,Caribbean,Monthly,783.330000,916.670000,231.250000,4079.170000
198,Togo,Africa,Monthly,787.960000,852.410000,214.310000,3786.720000
94,Iran,Asia,Monthly,932.630000,1070.970000,269.530000,4770.470000
64,Ethiopia,Africa,Monthly,143.880000,160.410000,40.420000,713.130000
118,Macedonia,Europe,Monthly,677.000000,794.140000,199.830000,3531.440000
58,Ecuador,South America,Monthly,1260.000000,1370.000000,340.000000,6080.000000
134,Mongolia,Asia,Monthly,515.760000,564.740000,142.340000,2509.620000
170,Saint Martin,North America,Monthly,3086.680000,3477.800000,877.380000,15433.400000
123,Mali,Africa,Monthly,478.580000,533.360000,134.550000,2368.710000
92,India,Asia,Monthly,327.970000,384.430000,97.070000,1717.920000
174,Sao Tome and Principe,Africa,Monthly,254.881630,298.782640,75.441552,1329.817200
180,Singapore,Asia,Monthly,5647.060000,6235.290000,1573.530000,27720.590000
129,Mayotte,Africa,Monthly,2389.010000,2748.410000,697.670000,12262.160000
0,Afghanistan,Asia,Monthly,853.740000,1001.150000,252.530000,4460.970000
22,Bermuda,Northern America,Monthly,1440.000000,1600.000000,400.000000,7120.000000
144,New Caledonia,Oceania,Monthly,664.300000,779.450000,196.630000,3463.240000
161,Portugal,Europe,Monthly,2537.000000,2917.550000,739.960000,13002.110000
219,Zambia,Africa,Monthly,0.261335,0.285524,0.072092,1.271103
155,Panama,Central America,Monthly,1890.000000,2130.000000,540.000000,9460.000000
70,French Polynesia,Oceania,Monthly,1133.750000,1293.180000,325.950000,5757.310000
188,Sudan,Africa,Monthly,67.610000,74.530000,18.800000,331.920000
153,Palau,Oceania,Monthly,2380.000000,2740.000000,690.000000,12200.000000
160,Poland,Europe,Monthly,1496.570000,1736.840000,437.070000,7734.550000
151,Oman,Asia,Monthly,3932.290000,4635.420000,1171.880000,20572.920000
37,Cayman Islands,Caribbean,Monthly,3430.970000,3901.560000,984.390000,17406.960000
20,Belize,Central America,Monthly,1730.000000,1965.000000,495.000000,8750.000000
207,United Arab Emirates,Asia,Monthly,3324.250000,3896.460000,708.450000,18637.600000
90,Hungary,Europe,Monthly,1227.460000,1344.230000,339.450000,5974.360000
202,Turkey,Asia,Monthly,254.100000,286.130000,72.080000,1274.120000
178,Seychelles,Africa,Monthly,1246.440000,1403.130000,353.990000,6246.440000
113,Libya,Africa,Monthly,417.180000,470.350000,118.610000,2085.890000
99,Japan,Asia,Monthly,3158.670000,3453.120000,869.970000,15391.820000
76,Gibraltar,Europe,Monthly,3567.070000,4135.370000,1046.340000,18393.900000
197,Thailand,Asia,Monthly,2432.280000,2662.110000,670.310000,11846.790000
16,Bangladesh,Asia,Monthly,218.570000,236.710000,59.680000,1052.060000
61,Equatorial Guinea,Africa,Monthly,671.940000,773.460000,194.980000,3432.220000
149,Northern Mariana Islands,Oceania,Monthly,1820.000000,1990.000000,500.000000,8870.000000
156,Papua New Guinea,Oceania,Monthly,1010.960000,1128.770000,284.930000,5013.700000
209,United States,Northern America,Monthly,6966.000000,7925.000000,2000.000000,35250.000000
28,British Indian Ocean Territory,Africa,Monthly,2360.000000,2690.000000,680.000000,12000.000000

In [92]:
df.columns

Index(['country_name', 'continent_name', 'wage_span', 'median_salary',
       'average_salary', 'lowest_salary', 'highest_salary'],
      dtype='object')

In [93]:
# In thông tin thuộc tính
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 221 entries, 0 to 220
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   country_name    221 non-null    object
 1   continent_name  221 non-null    object
 2   wage_span       221 non-null    object
 3   median_salary   221 non-null    float64
 4   average_salary  221 non-null    float64
 5   lowest_salary   221 non-null    float64
 6   highest_salary  221 non-null    float64
dtypes: float64(4), object(3)
memory usage: 12.2+ KB

In [94]:
# Kiểm tra giá trị N/A
df.isna().sum()

country_name      0
continent_name    0
wage_span         0
median_salary     0
average_salary    0
lowest_salary     0
highest_salary    0
dtype: int64

In [95]:
# Tóm tắt thuộc tính
df.describe()

       median_salary  average_salary  lowest_salary  highest_salary
count     221.000000      221.000000     221.000000      221.000000
mean     1762.631906     1982.339812     502.783204     8802.165619
std      1634.708716     1835.429193     470.073328     8140.210641
min         0.261335        0.285524       0.072092        1.271103
25%       567.210000      651.000000     163.930000     2900.480000
50%      1227.460000     1344.230000     339.450000     5974.360000
75%      2389.010000     2740.000000     690.000000    12050.740000
max      9836.070000    11292.900000    2850.270000    50363.930000

In [96]:
a = px.pie(df, names='continent_name', values='highest_salary', title='Thống kê mức thu nhập cao nhất theo từng châu lục')
a.show()

In [97]:
top_10 = df.sort_values('highest_salary', ascending=False).head(10)
a = px.bar(top_10, x='country_name', y='highest_salary', title='Top 10 quốc gia có mức thu nhập cao nhất', color='highest_salary')
a.show()

In [98]:
top_5 = df.sort_values('lowest_salary', ascending=True).head(5)
a = px.bar(top_5, x='country_name', y='lowest_salary', title='Top 5 quốc gia có mức thu nhập thấp nhất', color='country_name')
a.show()

In [99]:
top_10 = df.sort_values('median_salary', ascending=False).head(10)
a = px.bar(top_10, x='country_name', y='median_salary', title='Top 10 quốc gia có mức thu nhập trung vị cao nhất', color='median_salary')
a.show()